config:
  send_anonymous_usage_stats: False
  use_colors: True

simple_dbt_sqlite:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: '/app/dbsqlite/database_name.db'
      schema_directory: 'dbsqlite'
      #optional fields
      extensions:
        - "/app/dbsqlite/extension/crypto.so"